### ISSUE TITLE
Structural deletions

### ISSUE THREAD

**Issue by CarolynSBlack** [jamescummings/REED#10]
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L929-L930

https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L947

https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L949-L950

https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L952-L955

Please also note that while appendix value left under divs, the explanation should read: "This REED division is for the appendix section"

**Comment by jamescummings** [comment]
Done by @ajenhl
