### ISSUE TITLE
Added date @cert to schema

### ISSUE THREAD

**Issue by djakacki** [jamescummings/REED#14]
@jamescummings In order to get the files to validate in CWRC-Writer with date entities, I had to add this bit to the schema:

```
<!-- date: modify @cert -->
          <elementSpec ident="date" mode="change" module="core">
            <attList>
              <attDef ident="cert" mode="change">
                <valList mode="add" type="closed">
                  <valItem ident="definite">
                    <desc>There is a high degree of certainty about this date</desc>
                  </valItem>
                  <valItem ident="reasonably certain">
                    <desc>There is a moderate degree of certainty about this date</desc>
                  </valItem>
                  <valItem ident="probable">
                    <desc>There is a low degree of certainty about this date</desc>
                  </valItem>
                  <valItem ident="speculative">
                    <desc>The date is unknown</desc>
                  </valItem>
                </valList>
              </attDef>
            </attList>            
          </elementSpec>
```

**Comment by jamescummings** [comment]
@djakacki:  Are those value idents really the best?  
I mean definite/reasonably certain/probable/speculative seem just to be high/medium/low/unknown, right?

Or should we have them but maybe change reasonably certain to a single token? reasonablyCertain? fairlyCertain? quiteRightMLord?

**Comment by djakacki** [comment]
They seem to be synonymous ... CWRC-Writer uses the definite/reasonably certain ... etc. I'm talking to Mihaela about that. I'd be happier to go with high/medium/low/unknown since it's better practice.

**Comment by jamescummings** [comment]
The thing the really irks me is the space in 'reasonably certain'. While that is perfectly fine really, for some reason it has the same effect on my as when people say 'haitch' instead of 'aitch' for the 8th letter of the alphabet. I'm told I'm a purist.
