### ISSUE TITLE
changes to taxonomy.xml

### ISSUE THREAD

**Issue by CarolynSBlack** [jamescummings/REED#6]
Please change:

1) author_surname to authorSurname and shorten description to read "This idno is an author surname"
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L559

2) short_title to shortTitle and shorten description to read "This idno is a shortened title"
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L572

**Comment by jamescummings** [comment]
Done by @ajenhl
