### ISSUE TITLE
additions to taxonomy.xml

### ISSUE THREAD

**Issue by CarolynSBlack** [jamescummings/REED#7]
Please add:

`note type="edDesc"`
This note is the editorial note on a print source from which record/s were derived

`note type="techDesc"`
This note is the full bibliographic citation for a print source from which record/s were derived

`idno type="pubNumber"` (replacing `idno type="publication"`)
This idno is a publication given as an ID number

`idno type="publication"`
This idno is the name of a short-title catalogue

`ab type="techDesc"`
This ab is the technical description for a manuscript source from which record/s were derived

`ab type="edDesc"`
This ab is the editorial note on a manuscript source from which record/s were derived

**Comment by jamescummings** [comment]
Done by @ajenhl
