### ISSUE TITLE
additions to staff.xml

### ISSUE THREAD

**Issue by CarolynSBlack** [jamescummings/REED#8]
Please add: 

`floatingText`

`settingDesc` (will have `placeName` within it if that also needs to be added?)
This settingDesc identifies a particular REED collection.

`rs` may have "next" or "prev" attributes within it. Currently getting errors on these.

`date` may have "precision" attribute

`l`

`lg`

**Comment by jamescummings** [comment]
Done by @ajenhl;

(Though I'm curious how floatingText is being used and will follow that up.)
