### ISSUE TITLE
Deletions

### ISSUE THREAD

**Issue by CarolynSBlack** [jamescummings/REED#9]
There are a few ghosts from Fortune that we are no longer using. Please delete (overwritten, struckthrough, margin_left, margin_right, below, above, endnote, marginalia, STC_ref and Wing_ref, marginalia and publication and repository_shelfmark):

https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L65
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L68
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L130
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L133
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L366
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L387
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L640
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L645
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L666-L667
https://github.com/jamescummings/REED/blob/master/ODD/reed.odd#L669-L671

**Comment by jamescummings** [comment]
I believe all done by @ajenhl but not exhaustively.
